[package]
name = "rute_gen"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]

[dependencies]
pest = { git = "https://github.com/pest-parser/pest" }
pest_derive = { git = "https://github.com/pest-parser/pest" }
heck = "0.2.1"
argparse = "0.2.1"
liquid = "0.13"
