version: 2
updates:
- package-ecosystem: cargo
  directory: "/rute"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: libloading
    versions:
    - 0.6.0
