language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly

dist: xenial
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - binutils-dev
      - g++-6

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install qt5 &&
      export QT5="`brew --prefix qt5`";
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial --yes;
      sudo apt-get update;
      sudo apt-get install qt511base mesa-common-dev;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90;
      export QT5=/opt/qt511;
   fi

script:
  - cd rute && cargo build --example app && cd ..;
  - cd rute_gen && cargo test

after_success:
  # Coverage report
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
        tar xzf master.tar.gz &&
        cd kcov-master &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        sudo make install &&
        cd ../.. &&
        rm -rf kcov-master &&
        for file in target/debug/rute_gen-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
        bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage"
    fi
