// This file is auto-generated by rute_gen. DO NOT EDIT!
#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "../rute_base.h"

#ifdef __cplusplus
extern "C" {
#endif
#include "list_widget_item_ffi.h"

struct RUListWidgetFuncs;
struct RUListWidget;

typedef struct RUListWidgetFuncs {
    void (*destroy)(struct RUBase* self);
    void (*add_item)(struct RUBase* self_c, const char* label);
    void (*clear)(struct RUBase* self_c);
    struct RUArray (*selected_items)(struct RUBase* self_c);
    void (*add_widget_item)(struct RUBase* self_c, struct RUBase* item);
    void (*set_supported_drop_actions_event)(void* object, void* user_data,
                                             void* wrapped_func,
                                             uint32_t (*event)(void*,
                                                               void* self_c));
    void (*remove_supported_drop_actions)(void* object);
} RUListWidgetFuncs;

typedef struct RUListWidgetAllFuncs {
    struct RUObjectFuncs* object_funcs;
    struct RUPaintDeviceFuncs* paint_device_funcs;
    struct RUWidgetFuncs* widget_funcs;
    struct RUListWidgetFuncs* list_widget_funcs;
} RUListWidgetAllFuncs;

typedef struct RUListWidget {
    RUBase* qt_data;
    RUBase* host_data;
    struct RUListWidgetAllFuncs* all_funcs;
} RUListWidget;

extern RUListWidgetFuncs s_list_widget_funcs;
extern RUListWidgetAllFuncs s_list_widget_all_funcs;

#ifdef __cplusplus
}
#endif
