////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by rute_gen. DO NOT EDIT
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "../rute_base.h"
#include "../rute_manual.h"
#include <QMoveEvent>
#include "move_event_ffi.h"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static struct RUPoint move_event_pos(struct RUBase* self_c) {
    QMoveEvent* qt_value = (QMoveEvent*)self_c;
    auto ret_value = qt_value->pos();
    WRPoint* new_val = new WRPoint();
    *new_val = ret_value;
    struct RUPoint ctl;
    ctl.qt_data = (struct RUBase*)new_val;
    ctl.host_data = (struct RUBase*)s_host_data_lookup[(void*)new_val];
    ctl.all_funcs = &s_point_all_funcs;
    return ctl;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static struct RUPoint move_event_old_pos(struct RUBase* self_c) {
    QMoveEvent* qt_value = (QMoveEvent*)self_c;
    auto ret_value = qt_value->oldPos();
    WRPoint* new_val = new WRPoint();
    *new_val = ret_value;
    struct RUPoint ctl;
    ctl.qt_data = (struct RUBase*)new_val;
    ctl.host_data = (struct RUBase*)s_host_data_lookup[(void*)new_val];
    ctl.all_funcs = &s_point_all_funcs;
    return ctl;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct RUMoveEventFuncs s_move_event_funcs = {
    move_event_pos,
    move_event_old_pos,
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct RUMoveEventAllFuncs s_move_event_all_funcs = {
    &s_event_funcs,
    &s_move_event_funcs,
};

