// This file is auto-generated by rute_gen. DO NOT EDIT!

#include <map>
#include "rute_ffi.h"

static char s_temp_string_buffer[1024*1024];
std::map<void*, void*> s_host_data_lookup;
struct KeyVal { int val, key; };

const char* q_string_to_const_char(const QString& ret_value) {
    QByteArray ba = ret_value.toUtf8();
    const char* c_str = ba.data();
    assert((ba.size() + 1) < sizeof(s_temp_string_buffer), "buffer not large enough");
    memcpy(s_temp_string_buffer, c_str, ba.size() + 1);
    return s_temp_string_buffer;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static struct Rute s_rute = {
    nullptr,
    create_application,
    get_application,
    create_font,
    create_list_widget,
    create_list_widget_item,
    create_widget,
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifdef _WIN32
extern "C" __declspec(dllexport) struct Rute* rute_get() {
#else
extern "C" struct Rute* rute_get() {
#endif
    return (Rute*)&s_rute;
}

