////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by rute_gen. DO NOT EDIT
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "../rute_base.h"
#include "../rute_manual.h"
#include <QTouchEvent>
#include "touch_event_ffi.h"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static struct RUWindow touch_event_window(struct RUBase* self_c) {
    QTouchEvent* qt_value = (QTouchEvent*)self_c;
    auto ret_value = qt_value->window();
    struct RUWindow ctl;
    ctl.qt_data = (struct RUBase*)ret_value;
    ctl.host_data = (struct RUBase*)s_host_data_lookup[(void*)ret_value];
    ctl.all_funcs = &s_window_all_funcs;
    return ctl;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static struct RUObject touch_event_target(struct RUBase* self_c) {
    QTouchEvent* qt_value = (QTouchEvent*)self_c;
    auto ret_value = qt_value->target();
    struct RUObject ctl;
    ctl.qt_data = (struct RUBase*)ret_value;
    ctl.host_data = (struct RUBase*)s_host_data_lookup[(void*)ret_value];
    ctl.all_funcs = &s_object_all_funcs;
    return ctl;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

static uint32_t touch_event_touch_point_states(struct RUBase* self_c) {
    QTouchEvent* qt_value = (QTouchEvent*)self_c;
    auto ret_value = qt_value->touchPointStates();
    return (uint32_t)ret_value;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct RUTouchEventFuncs s_touch_event_funcs = {
    touch_event_window,
    touch_event_target,
    touch_event_touch_point_states,
};

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

struct RUTouchEventAllFuncs s_touch_event_all_funcs = {
    &s_event_funcs,
    &s_input_event_funcs,
    &s_touch_event_funcs,
};

