// This file is auto-generated by rute_gen. DO NOT EDIT.
use rute_ffi_base::*;

#[allow(unused_imports)]
use auto::drag_move_event_ffi::*;
#[allow(unused_imports)]
use auto::drop_event_ffi::*;
#[allow(unused_imports)]
use auto::event_ffi::*;
#[allow(unused_imports)]
use std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUDragEnterEventFuncs {}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUDragEnterEventAllFuncs {
    pub event_funcs: *const RUEventFuncs,
    pub drop_event_funcs: *const RUDropEventFuncs,
    pub drag_move_event_funcs: *const RUDragMoveEventFuncs,
    pub drag_enter_event_funcs: *const RUDragEnterEventFuncs,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUDragEnterEvent {
    pub qt_data: *const RUBase,
    pub host_data: *const RUBase,
    pub all_funcs: *const RUDragEnterEventAllFuncs,
}
