// This file is auto-generated by rute_gen. DO NOT EDIT.
use rute_ffi_base::*;

#[allow(unused_imports)]
use std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUFontInfoFuncs {
    pub swap: extern "C" fn(self_c: *const RUBase, other: *const RUBase),
    pub family: extern "C" fn(self_c: *const RUBase) -> *const ::std::os::raw::c_char,
    pub style_name: extern "C" fn(self_c: *const RUBase) -> *const ::std::os::raw::c_char,
    pub pixel_size: extern "C" fn(self_c: *const RUBase) -> i32,
    pub point_size: extern "C" fn(self_c: *const RUBase) -> i32,
    pub point_size_f: extern "C" fn(self_c: *const RUBase) -> f32,
    pub italic: extern "C" fn(self_c: *const RUBase) -> bool,
    pub weight: extern "C" fn(self_c: *const RUBase) -> i32,
    pub bold: extern "C" fn(self_c: *const RUBase) -> bool,
    pub underline: extern "C" fn(self_c: *const RUBase) -> bool,
    pub overline: extern "C" fn(self_c: *const RUBase) -> bool,
    pub fixed_pitch: extern "C" fn(self_c: *const RUBase) -> bool,
    pub style_hint: extern "C" fn(self_c: *const RUBase) -> i32,
    pub raw_mode: extern "C" fn(self_c: *const RUBase) -> bool,
    pub exact_match: extern "C" fn(self_c: *const RUBase) -> bool,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUFontInfoAllFuncs {
    pub font_info_funcs: *const RUFontInfoFuncs,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUFontInfo {
    pub qt_data: *const RUBase,
    pub host_data: *const RUBase,
    pub all_funcs: *const RUFontInfoAllFuncs,
}
