// This file is auto-generated by rute_gen. DO NOT EDIT.
use rute_ffi_base::*;

#[allow(unused_imports)]
use auto::point_ffi::RUPoint;
#[allow(unused_imports)]
use std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUPointFFuncs {
    pub destroy: extern "C" fn(self_c: *const RUBase),
    pub manhattan_length: extern "C" fn(self_c: *const RUBase) -> f32,
    pub is_null: extern "C" fn(self_c: *const RUBase) -> bool,
    pub x: extern "C" fn(self_c: *const RUBase) -> f32,
    pub y: extern "C" fn(self_c: *const RUBase) -> f32,
    pub set_x: extern "C" fn(self_c: *const RUBase, x: f32),
    pub set_y: extern "C" fn(self_c: *const RUBase, y: f32),
    pub rx: extern "C" fn(self_c: *const RUBase) -> f32,
    pub ry: extern "C" fn(self_c: *const RUBase) -> f32,
    pub dot_product:
        extern "C" fn(self_c: *const RUBase, p1: *const RUBase, p2: *const RUBase) -> f32,
    pub to_point: extern "C" fn(self_c: *const RUBase) -> RUPoint,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUPointFAllFuncs {
    pub point_f_funcs: *const RUPointFFuncs,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUPointF {
    pub qt_data: *const RUBase,
    pub host_data: *const RUBase,
    pub all_funcs: *const RUPointFAllFuncs,
}
