// This file is auto-generated by rute_gen. DO NOT EDIT.
use rute_ffi_base::*;

#[allow(unused_imports)]
use auto::abstract_button_ffi::*;
#[allow(unused_imports)]
use auto::object_ffi::*;
#[allow(unused_imports)]
use auto::paint_device_ffi::*;
#[allow(unused_imports)]
use auto::widget_ffi::*;
#[allow(unused_imports)]
use std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUToolButtonFuncs {
    pub destroy: extern "C" fn(self_c: *const RUBase),
    pub tool_button_style: extern "C" fn(self_c: *const RUBase) -> i32,
    pub arrow_type: extern "C" fn(self_c: *const RUBase) -> i32,
    pub set_arrow_type: extern "C" fn(self_c: *const RUBase, arrow_type: i32),
    pub set_popup_mode: extern "C" fn(self_c: *const RUBase, mode: i32),
    pub popup_mode: extern "C" fn(self_c: *const RUBase) -> i32,
    pub auto_raise: extern "C" fn(self_c: *const RUBase) -> bool,
    pub show_menu: extern "C" fn(self_c: *const RUBase),
    pub set_tool_button_style: extern "C" fn(self_c: *const RUBase, style: i32),
    pub set_mouse_press_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_mouse_press_event: extern "C" fn(object: *const RUBase),

    pub set_mouse_release_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_mouse_release_event: extern "C" fn(object: *const RUBase),

    pub set_paint_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_paint_event: extern "C" fn(object: *const RUBase),

    pub set_enter_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_enter_event: extern "C" fn(object: *const RUBase),

    pub set_leave_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_leave_event: extern "C" fn(object: *const RUBase),

    pub set_change_event: extern "C" fn(
        object: *const RUBase,
        user_data: *const c_void,
        trampoline_func: *const c_void,
        callback: *const c_void,
    ),

    pub remove_change_event: extern "C" fn(object: *const RUBase),
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUToolButtonAllFuncs {
    pub object_funcs: *const RUObjectFuncs,
    pub paint_device_funcs: *const RUPaintDeviceFuncs,
    pub widget_funcs: *const RUWidgetFuncs,
    pub abstract_button_funcs: *const RUAbstractButtonFuncs,
    pub tool_button_funcs: *const RUToolButtonFuncs,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUToolButton {
    pub qt_data: *const RUBase,
    pub host_data: *const RUBase,
    pub all_funcs: *const RUToolButtonAllFuncs,
}
