// This file is auto-generated by rute_gen. DO NOT EDIT.
use rute_ffi_base::*;

#[allow(unused_imports)]
use auto::event_ffi::*;
#[allow(unused_imports)]
use auto::input_event_ffi::*;
#[allow(unused_imports)]
use auto::object_ffi::RUObject;
#[allow(unused_imports)]
use auto::window_ffi::RUWindow;
#[allow(unused_imports)]
use std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUTouchEventFuncs {
    pub window: extern "C" fn(self_c: *const RUBase) -> RUWindow,
    pub target: extern "C" fn(self_c: *const RUBase) -> RUObject,
    pub touch_point_states: extern "C" fn(self_c: *const RUBase) -> i32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUTouchEventAllFuncs {
    pub event_funcs: *const RUEventFuncs,
    pub input_event_funcs: *const RUInputEventFuncs,
    pub touch_event_funcs: *const RUTouchEventFuncs,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct RUTouchEvent {
    pub qt_data: *const RUBase,
    pub host_data: *const RUBase,
    pub all_funcs: *const RUTouchEventAllFuncs,
}
