[package]
name = "rute"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
build = "build.rs"

[dependencies]
libloading = "0.5"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
